add blastn screening

diff --git a/ccfind b/ccfind
--- a/ccfind
+++ b/ccfind
@@ -7,11 +7,12 @@
 #
 
 PROGNAME=$(basename $0)
-VERSION="1.1.1"
+VERSION="1.2.0"
 PROGNAMEc="[35m$PROGNAME[0m"
 Errmsg="[31m[error][0m"
 Sccmsg="[32m[success][0m"
-Moddate="2018-02-08"
+Moddate="2018-07-17"
+incmd="$0 $*"
 
 
 # {{{ usage
@@ -19,32 +20,43 @@ read -r -d '' usage <<EOF
 [35m### $PROGNAME ver $VERSION ($Moddate) ###
 
 [32m[description][0m
-$PROGNAME - tool to find circular complete sequence by detecting terminal redundancy
+$PROGNAME is tool to find circular complete sequence by detecting terminal redundancy.
 
-$PROGNAME is originally designed to find circular complete contigs/scaffolds generated by the SPAdes assembler. 
-$PROGNAME may be applicable for sequences generated by other assemblers, but not tested.
+$PROGNAME is originally designed to find circular complete contigs generated by the SPAdes assembler. 
+$PROGNAME can be used for any contig/genome, but cutoff values (see below) should be carefully considered.
 
 [32m[dependencies][0m
-- ssearch36        -- included in FASTA program version 36
-                      (http://fasta.bioch.virginia.edu/fasta_www2/fasta_list2.shtml)
+- ssearch        -- included in FASTA program
+                    (available here: http://fasta.bioch.virginia.edu/fasta_www2/fasta_list2.shtml)
+- blastn         -- included in the BLAST+ program;
+                    (available here: https://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE_TYPE=BlastDocs&DOC_TYPE=Download)
 - ruby (ver >=2.0) 
 
 [32m[usage][0m
 $ $PROGNAME <input fasta> <output dir> [-i <min %identity> -l <min aligned len> -L <terminal fragment size>]
 
+- <output dir> should not exist.
+
 [32m[options][0m
+  (general)
     -h, --help
     -v, --version
+
+  (cutoff values)
+    -L, --terminal-fragment-size  [int] (default: 500) -- This should be longer than estimated terminal redundancy length. If input length is less than 2 x (this value), the sequence will be ignored and listed in "result/01.skipped.list".
     -i, --min-percent-identity    [int] (default: 94)
     -l, --min-aligned-length      [int] (default: 50)
-    -L, --terminal-fragment-size  [int] (default: 500)
+
+  (use GNU parallel)
+    --ncpus        [int]    -- number of jobs in parallel	
+
+  (for icr user)            -- for computation in the ICR supercomputer system
+    --queue        [JP1]    -- queue for computation
 
 [32m[output files][0m
-result/05.circ.detected.out -- list of sequences with TR
-result/05.circ.noTR.fasta   -- modified input sequences by removing TR in the end of sequence.
-
-Please note that very short sequences that are less than 2 x terminal fragment size (1,000 nt in case of default value) will not be tested.
-These sequences will be logged in the file: result/01.skipped.list
+result/05.circ.detected.out -- list of sequence with terminal redundancy.s
+result/05.circ.fasta        -- fasta file of sequences with terminal redundancy.
+result/05.circ.noTR.fasta   -- fasta file of sequences with terminal redundancy, but the detected terminal redundnacy at the end of sequence is removed.
 EOF
 # }}} usage
 
@@ -66,7 +78,7 @@ do
 				echo "$PROGNAME: option requires an argument -- $1" 1>&2
 				exit 1
 			fi
-			Idt="$2"
+			idt="$2"
 			shift 2
 			;;
 		'-l'|'--min-aligned-length' )
@@ -74,7 +86,7 @@ do
 				echo "$PROGNAME: option requires an argument -- $1" 1>&2
 				exit 1
 			fi
-			Len="$2"
+			len="$2"
 			shift 2
 			;;
 		'-L'|'--terminal-fragment-size' )
@@ -82,7 +94,31 @@ do
 				echo "$PROGNAME: option requires an argument -- $1" 1>&2
 				exit 1
 			fi
-			Size="$2"
+			size="$2"
+			shift 2
+			;;
+		'--queue' )
+			if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]] ; then
+				echo "$Errmsg option requires an argument -- $1" 1>&2
+				exit 1
+			fi
+			queue="$2"
+			shift 2
+			;;
+		'--ncpus' )
+			if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]] ; then
+				echo "$Errmsg option requires an argument -- $1" 1>&2
+				exit 1
+			fi
+			ncpus="$2"
+			shift 2
+			;;
+		'--wtime' )
+			if [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]] ; then
+				echo "$Errmsg option requires an argument -- $1" 1>&2
+				exit 1
+			fi
+			wtime="$2"
 			shift 2
 			;;
 		'--'|'-' )
@@ -126,10 +162,19 @@ fi
 ### check availablity of ssearch36
 command -v ssearch36 >/dev/null 2>&1 || { echo >&2 "ssearch36 is required but not available.  Aborting."; exit 1; }
 
+### check availablity of blastn
+command -v blastn >/dev/null 2>&1 || { echo >&2 "$Errmsg blastn (in BLAST+ package) is required but not available.  Aborting."; exit 1; }
+command -v makeblastdb >/dev/null 2>&1 || { echo >&2 "$Errmsg makeblastdb (in BLAST+ package) is required but not available.  Aborting."; exit 1; }
+
 ### check ruby version
 ST=`ruby -e 'print RUBY_VERSION.to_f >= 2.0 ? 0 : 1'`
 if [ $ST -ne 0 ]; then 
 	echo >&2 "ruby (version >=2.0) is required.  Aborting."; exit 1;
+fi
+
+### check availablity of GNU parallel
+if [ -n $ncpus ]; then 
+	command -v parallel >/dev/null 2>&1 || { echo >&2 "$Errmsg GNU parallel is required but not available.  Aborting."; exit 1; }
 fi
 # }}} check dependencies
 
@@ -138,9 +183,12 @@ fi
 ### parse args and default params
 fin=${params[0]}
 dir=${params[1]}
-Idt="${Idt:-94}"
-Len="${Len:-50}"
-Size="${Size:-500}"
+idt="${idt:-94}"
+len="${len:-50}"
+size="${size:-500}"
+queue="${queue}"
+nthread="${nthread:-1}"
+wtime="${wtime:-24:00:00}"
 
 ### rakefile and log directory
 pushd `dirname $0` > /dev/null
@@ -157,7 +205,8 @@ function after_run(){
   endTime=$(LC_ALL=C date +"%Y-%m-%d %H:%M:%S %z")
 
   if [[ $1 -gt 0 ]] ; then
-    echo "$Errmsg run failed: $endTime\nCheck log dir -- $logdir" > "$logdir/$startTime.$jobname.error"
+    echo "$Errmsg run failed: $endTime" > "$logdir/$startTime.$jobname.error"
+    echo "$Errmsg process is killed: $endTime" |tee -a "$logdir/$jobname.log"
     exit 1
   else
     echo "$Sccmsg run finished: $endTime" > "$logdir/$startTime.$jobname.success"
@@ -166,35 +215,36 @@ function after_run(){
 ### }}} after run function
 
 
+# {{{ input command
+read -r -d '' incmdlog <<EOF
+
+[1;32m===== command line[0m
+
+$ $incmd
+
+[1;32m===== log file[0m
+
+$logdir/$jobname.log
+
+[1;32m===== check version: $PROGNAME[0m
+
+$VERSION
+
+EOF
+# }}} input command
+
+
 ### main
 mkdir -p $logdir
 startTime=$(LC_ALL=C date +"%Y-%m-%d %H:%M:%S")
+
+## write input command
+echo "$incmdlog" |tee -a $logdir/$jobname.log
 
 ## trap Ctrl-C etc...
 trap 'after_run 1' 1 2 3 9 15
 
 ### run
-rake 01.make_term_fasta          -f $rakefile dir="$dir" fin="$fin" Size="$Size"            >$logdir/01.stdout 2>$logdir/01.stderr; ST=$?; echo $ST >$logdir/01.exitst
-
-if [ $ST -eq 0 ]; then 
-	rake 02.ssearch                  -f $rakefile dir="$dir"                                    >$logdir/02.stdout 2>$logdir/02.stderr; ST=$?; echo $ST >$logdir/02.exitst
-fi
-if [ $ST -eq 0 ]; then 
-	rake 03.parse_ssearch            -f $rakefile dir="$dir"                         Len="$Len" >$logdir/03.stdout 2>$logdir/03.stderr; ST=$?; echo $ST >$logdir/03.exitst
-fi
-if [ $ST -eq 0 ]; then 
-	rake 04.aln_extend_to_term       -f $rakefile dir="$dir"            Size="$Size"            >$logdir/04.stdout 2>$logdir/04.stderr; ST=$?; echo $ST >$logdir/04.exitst
-fi
-if [ $ST -eq 0 ]; then 
-	rake 05.make_circ_list_and_fasta -f $rakefile dir="$dir" fin="$fin" Size="$Size" Idt="$Idt" >$logdir/05.stdout 2>$logdir/05.stderr; ST=$?; echo $ST >$logdir/05.exitst
-fi
+rake -f $rakefile dir="$dir" fin="$fin" size="$size" len="$len" idt="$idt" queue="$queue" ncpus="$ncpus" wtime="$wtime" 2>&1 |tee -a $logdir/$jobname.log
+st=$(( ${PIPESTATUS[0]} + ${PIPESTATUS[1]} ))
 after_run $ST
-
-# if [ $ST -eq 0 ]; then 
-# 	echo "finished at: $(LC_ALL=C date)" > $logdir/success
-# else
-# 	echo "[error] something wrong" 1>&2
-# 	echo "Please check log dir -- $logdir"
-# 	echo "finished at: $(LC_ALL=C date)" > $logdir/error
-# 	exit 1
-# fi
