usage is colored

diff --git a/ccfind b/ccfind
--- a/ccfind
+++ b/ccfind
@@ -7,40 +7,44 @@
 #
 
 PROGNAME=$(basename $0)
-VERSION="1.1"
+VERSION="1.1.1"
+PROGNAMEc="[35m$PROGNAME[0m"
+Errmsg="[31m[error][0m"
+Sccmsg="[32m[success][0m"
+Moddate="2018-02-08"
 
 
 # {{{ usage
 read -r -d '' usage <<EOF
-=== $PROGNAME version $VERSION ===
+[35m### $PROGNAME ver $VERSION ($Moddate) ###
 
-[description]
+[32m[description][0m
 $PROGNAME - tool to find circular complete sequence by detecting terminal redundancy
 
 $PROGNAME is originally designed to find circular complete contigs/scaffolds generated by the SPAdes assembler. 
 $PROGNAME may be applicable for sequences generated by other assemblers, but not tested.
 
-[dependencies]
-- ssearch36        -- included in the FASTA program version 36
+[32m[dependencies][0m
+- ssearch36        -- included in FASTA program version 36
                       (http://fasta.bioch.virginia.edu/fasta_www2/fasta_list2.shtml)
 - ruby (ver >=2.0) 
 
-[usage]
+[32m[usage][0m
 $ $PROGNAME <input fasta> <output dir> [-i <min %identity> -l <min aligned len> -L <terminal fragment size>]
 
-[options]
+[32m[options][0m
     -h, --help
     -v, --version
     -i, --min-percent-identity    [int] (default: 94)
     -l, --min-aligned-length      [int] (default: 50)
     -L, --terminal-fragment-size  [int] (default: 500)
 
-[output files]
+[32m[output files][0m
 result/05.circ.detected.out -- list of sequences with TR
 result/05.circ.noTR.fasta   -- modified input sequences by removing TR in the end of sequence.
 
-Please note that very short sequences that are less than 2 x terminal fragment size (1,000 nt by default) will not be tested.
-These sequences are logged in the file: result/01.skipped.list
+Please note that very short sequences that are less than 2 x terminal fragment size (1,000 nt in case of default value) will not be tested.
+These sequences will be logged in the file: result/01.skipped.list
 EOF
 # }}} usage
 
@@ -118,6 +122,7 @@ fi
 # }}} parse options
 
 
+# {{{ check dependencies
 ### check availablity of ssearch36
 command -v ssearch36 >/dev/null 2>&1 || { echo >&2 "ssearch36 is required but not available.  Aborting."; exit 1; }
 
@@ -126,7 +131,10 @@ ST=`ruby -e 'print RUBY_VERSION.to_f >= 2.0 ? 0 : 1'`
 if [ $ST -ne 0 ]; then 
 	echo >&2 "ruby (version >=2.0) is required.  Aborting."; exit 1;
 fi
+# }}} check dependencies
 
+
+# {{{ assign variables 
 ### parse args and default params
 fin=${params[0]}
 dir=${params[1]}
@@ -141,12 +149,33 @@ popd > /dev/null
 jobname=`basename $0`
 rakefile=$scrdir/$jobname.rake
 logdir=$dir/log
-mkdir -p $logdir
+# }}} assign variables 
+
+
+# {{{ after run function
+function after_run(){
+  endTime=$(LC_ALL=C date +"%Y-%m-%d %H:%M:%S %z")
+
+  if [[ $1 -gt 0 ]] ; then
+    echo "$Errmsg run failed: $endTime\nCheck log dir -- $logdir" > "$logdir/$startTime.$jobname.error"
+    exit 1
+  else
+    echo "$Sccmsg run finished: $endTime" > "$logdir/$startTime.$jobname.success"
+  fi
+}
+### }}} after run function
+
 
 ### main
-if [ -d $logdir ]; then
-	rake 01.make_term_fasta          -f $rakefile dir="$dir" fin="$fin" Size="$Size"            >$logdir/01.stdout 2>$logdir/01.stderr; ST=$?; echo $ST >$logdir/01.exitst
-fi
+mkdir -p $logdir
+startTime=$(LC_ALL=C date +"%Y-%m-%d %H:%M:%S")
+
+## trap Ctrl-C etc...
+trap 'after_run 1' 1 2 3 9 15
+
+### run
+rake 01.make_term_fasta          -f $rakefile dir="$dir" fin="$fin" Size="$Size"            >$logdir/01.stdout 2>$logdir/01.stderr; ST=$?; echo $ST >$logdir/01.exitst
+
 if [ $ST -eq 0 ]; then 
 	rake 02.ssearch                  -f $rakefile dir="$dir"                                    >$logdir/02.stdout 2>$logdir/02.stderr; ST=$?; echo $ST >$logdir/02.exitst
 fi
@@ -159,12 +188,13 @@ fi
 if [ $ST -eq 0 ]; then 
 	rake 05.make_circ_list_and_fasta -f $rakefile dir="$dir" fin="$fin" Size="$Size" Idt="$Idt" >$logdir/05.stdout 2>$logdir/05.stderr; ST=$?; echo $ST >$logdir/05.exitst
 fi
+after_run $ST
 
-if [ $ST -eq 0 ]; then 
-	echo "finished at: $(LC_ALL=C date)" > $logdir/success
-else
-	echo "[error] something wrong" 1>&2
-	echo "Please check log dir -- $logdir"
-	echo "finished at: $(LC_ALL=C date)" > $logdir/error
-	exit 1
-fi
+# if [ $ST -eq 0 ]; then 
+# 	echo "finished at: $(LC_ALL=C date)" > $logdir/success
+# else
+# 	echo "[error] something wrong" 1>&2
+# 	echo "Please check log dir -- $logdir"
+# 	echo "finished at: $(LC_ALL=C date)" > $logdir/error
+# 	exit 1
+# fi
