implementation of circular permutation, not to split any ORF into two fragments

diff --git a/ccfind b/ccfind
--- a/ccfind
+++ b/ccfind
@@ -7,11 +7,11 @@
 #
 
 PROGNAME=$(basename $0)
-VERSION="1.2.0"
+VERSION="1.3.0"
 PROGNAMEc="[35m$PROGNAME[0m"
 Errmsg="[31m[error][0m"
 Sccmsg="[32m[success][0m"
-Moddate="2018-07-17"
+Moddate="2018-07-27"
 incmd="$0 $*"
 
 
@@ -26,10 +26,13 @@ $PROGNAME is originally designed to find circular complete contigs generated by 
 $PROGNAME can be used for any contig/genome, but cutoff values (see below) should be carefully considered.
 
 [32m[dependencies][0m
-- ssearch        -- included in FASTA program
-                    (available here: http://fasta.bioch.virginia.edu/fasta_www2/fasta_list2.shtml)
-- blastn         -- included in the BLAST+ program;
-                    (available here: https://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE_TYPE=BlastDocs&DOC_TYPE=Download)
+- ssearch        -- for Smith-Waterman search, included in FASTA program
+                    (http://fasta.bioch.virginia.edu/fasta_www2/fasta_list2.shtml)
+- blastn         -- nucleotide blast, included in the BLAST+ program;
+                    (https://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE_TYPE=BlastDocs&DOC_TYPE=Download)
+- prodigal       -- for gene prediction. used for circular permutation arrangement of circularly detected sequences.
+                    Rightmost intergenic region is selected as termini.
+										(https://github.com/hyattpd/Prodigal)
 - ruby (ver >=2.0) 
 
 [32m[usage][0m
@@ -48,15 +51,16 @@ $ $PROGNAME <input fasta> <output dir> [options]
     -l, --min-aligned-length      [int] (default: 50)
 
   (use GNU parallel)
-    --ncpus        [int]    -- number of jobs in parallel	
+    --ncpus        [int]        -- number of jobs in parallel	
 
-  (for icr user)            -- for computation in the ICR supercomputer system
-    --queue        [JP1]    -- queue for computation
+  (for icr user)                -- for computation in the ICR supercomputer system
+    --queue        [JP1]        -- queue for computation
 
 [32m[output files][0m
-result/05.circ.detected.out -- list of sequence with terminal redundancy.
-result/05.circ.fasta        -- fasta file of sequences with terminal redundancy.
-result/05.circ.noTR.fasta   -- fasta file of sequences with terminal redundancy, but the detected terminal redundnacy at the end of sequence is removed.
+result/circ.detected.list    -- list of circular sequence.
+result/circ.fasta            -- fasta file of circular sequences. Terminal redundancy is keeped.
+result/circ.noTR.fasta       -- fasta file of circular sequences. Terminal redundancy is trimmed.
+result/circ.noTR.cPerm.fasta -- fasta file of circular sequences. Terminal redundancy is trimmed and circular permutation is perfomred, trying not to split any ORF into two fragments (the rightmost intergenic region detected by prodigal is selected as termini).
 EOF
 # }}} usage
 
@@ -160,11 +164,14 @@ fi
 
 # {{{ check dependencies
 ### check availablity of ssearch36
-command -v ssearch36 >/dev/null 2>&1 || { echo >&2 "ssearch36 is required but not available.  Aborting."; exit 1; }
+command -v ssearch36 >/dev/null 2>&1 || { echo >&2 "ssearch36 is required but not found.  Aborting."; exit 1; }
 
 ### check availablity of blastn
-command -v blastn >/dev/null 2>&1 || { echo >&2 "$Errmsg blastn (in BLAST+ package) is required but not available.  Aborting."; exit 1; }
-command -v makeblastdb >/dev/null 2>&1 || { echo >&2 "$Errmsg makeblastdb (in BLAST+ package) is required but not available.  Aborting."; exit 1; }
+command -v blastn >/dev/null 2>&1 || { echo >&2 "$Errmsg blastn (BLAST+ package) is required but not found.  Aborting."; exit 1; }
+command -v makeblastdb >/dev/null 2>&1 || { echo >&2 "$Errmsg makeblastdb (BLAST+ package) is required but not found.  Aborting."; exit 1; }
+
+### check availablity of prodigal
+command -v prodigal >/dev/null 2>&1 || { echo >&2 "prodigal is required but not found. Aborting."; exit 1; }
 
 ### check ruby version
 ST=`ruby -e 'print RUBY_VERSION.to_f >= 2.0 ? 0 : 1'`
@@ -174,7 +181,7 @@ fi
 
 ### check availablity of GNU parallel
 if [ -n $ncpus ]; then 
-	command -v parallel >/dev/null 2>&1 || { echo >&2 "$Errmsg GNU parallel is required but not available.  Aborting."; exit 1; }
+	command -v parallel >/dev/null 2>&1 || { echo >&2 "$Errmsg GNU parallel is required for parallel computation but not found.  Aborting."; exit 1; }
 fi
 # }}} check dependencies
 
